import{a as S,S as q,i}from"./assets/vendor-B-D547pe.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const P="https://pixabay.com/api/",M="49633368-6da3d74b0c3b6468a6c14afef";async function h(s,o){try{return(await S.get(P,{params:{key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(t){throw console.error("Error fetching images:",t),new Error("Failed to fetch images")}}h();let E=new q(".gallery a",{captionsData:"alt",captionDelay:250});const p=document.querySelector(".gallery");function m(s){const o=s.map(t=>`
      <li class="gallery-item">
            <a class="gallery-link" href = '${t.largeImageURL}'>
                <img class="gallery-image" src = '${t.webformatURL}' alt = '${t.tags}' width = '360'>
            </a>
            <div class = 'info'>
                <div class='descr'><h3>Likes</h3><p>${t.likes}</p></div>
                <div class='descr'><h3>Views</h3><p>${t.views}</p></div>
                <div class='descr'><h3>Comments</h3><p> ${t.comments}</p></div>
                <div class='descr'><h3>Downloads</h3><p>${t.downloads}</p></div>
            </div>
       </li>`).join("");p.insertAdjacentHTML("beforeend",o),E.refresh()}function u(){p.innerHTML=""}const g=document.querySelector(".loader");function v(){g.classList.add("is-active")}function f(){g.classList.remove("is-active")}const y=document.querySelector(".load-more");function w(){y.classList.add("is-active")}function c(){y.classList.remove("is-active")}f();const L=document.querySelector(".form"),$=L.querySelector("input");let l="",n=1;const b=15;L.addEventListener("submit",async s=>{if(s.preventDefault(),u(),n=1,l=$.value.trim(),!l){i.show({message:"Please enter a search term",position:"topCenter",color:"yellow"});return}v();try{const o=await h(l,n),t=o.totalHits,a=Math.ceil(t/b);o.hits.length?(m(o.hits),a>1?w():(c(),i.show({message:"We're sorry, but you've reached the end of search results",position:"bottomCenter",color:"red"}))):(u(),c(),i.show({message:"Sorry, there are no images matching your search query. Please try again! ",position:"center",color:"red"}))}catch{u(),c(),i.show({message:"We're sorry, but you've reached the end of search results",position:"center",color:"red"})}f()});y.addEventListener("click",async()=>{n+=1,v();try{const s=await h(l,n),o=s.totalHits,t=Math.ceil(o/b);m(s.hits);const a=document.querySelector(".gallery-item"),{height:e}=a.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),n<t?w():(c(),i.show({message:"We're sorry, but you've reached the end of search results",position:"bottomCenter",color:"red"}))}catch{c(),i.show({message:"We're sorry, but you've reached the end of search results",position:"bottomCenter",color:"red"})}finally{f()}});
//# sourceMappingURL=index.js.map
